/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface EscrowMinionInterface extends ethers.utils.Interface {
  functions: {
    "actions(address,uint256)": FunctionFragment;
    "cancelAction(uint256,address)": FunctionFragment;
    "executeAction(uint256,address)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "proposeTribute(address,address,address,uint256,address,uint256,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "actions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAction",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAction",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTribute",
    values: [string, string, string, BigNumberish, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "actions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTribute",
    data: BytesLike
  ): Result;

  events: {
    "ActionCanceled(uint256,address)": EventFragment;
    "ExecuteAction(uint256,address,address)": EventFragment;
    "ProposeAction(uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ActionCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecuteAction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposeAction"): EventFragment;
}

export class EscrowMinion extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: EscrowMinionInterface;

  functions: {
    actions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      tokenAddress: string;
      tokenId: BigNumber;
      vaultAddress: string;
      proposer: string;
      applicant: string;
      executed: boolean;
      0: string;
      1: BigNumber;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;

    "actions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      tokenAddress: string;
      tokenId: BigNumber;
      vaultAddress: string;
      proposer: string;
      applicant: string;
      executed: boolean;
      0: string;
      1: BigNumber;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;

    cancelAction(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelAction(uint256,address)"(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeAction(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeAction(uint256,address)"(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    proposeTribute(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "proposeTribute(address,address,address,uint256,address,uint256,string)"(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  actions(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    tokenAddress: string;
    tokenId: BigNumber;
    vaultAddress: string;
    proposer: string;
    applicant: string;
    executed: boolean;
    0: string;
    1: BigNumber;
    2: string;
    3: string;
    4: string;
    5: boolean;
  }>;

  "actions(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    tokenAddress: string;
    tokenId: BigNumber;
    vaultAddress: string;
    proposer: string;
    applicant: string;
    executed: boolean;
    0: string;
    1: BigNumber;
    2: string;
    3: string;
    4: string;
    5: boolean;
  }>;

  cancelAction(
    _proposalId: BigNumberish,
    molochAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelAction(uint256,address)"(
    _proposalId: BigNumberish,
    molochAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeAction(
    proposalId: BigNumberish,
    molochAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeAction(uint256,address)"(
    proposalId: BigNumberish,
    molochAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "onERC721Received(address,address,uint256,bytes)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  proposeTribute(
    applicant: string,
    molochAddress: string,
    tokenAddress: string,
    tokenId: BigNumberish,
    vaultAddress: string,
    requestAmount: BigNumberish,
    details: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "proposeTribute(address,address,address,uint256,address,uint256,string)"(
    applicant: string,
    molochAddress: string,
    tokenAddress: string,
    tokenId: BigNumberish,
    vaultAddress: string,
    requestAmount: BigNumberish,
    details: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    actions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      tokenAddress: string;
      tokenId: BigNumber;
      vaultAddress: string;
      proposer: string;
      applicant: string;
      executed: boolean;
      0: string;
      1: BigNumber;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;

    "actions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      tokenAddress: string;
      tokenId: BigNumber;
      vaultAddress: string;
      proposer: string;
      applicant: string;
      executed: boolean;
      0: string;
      1: BigNumber;
      2: string;
      3: string;
      4: string;
      5: boolean;
    }>;

    cancelAction(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelAction(uint256,address)"(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    executeAction(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeAction(uint256,address)"(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    proposeTribute(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposeTribute(address,address,address,uint256,address,uint256,string)"(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    ActionCanceled(proposalId: null, moloch: null): EventFilter;

    ExecuteAction(proposalId: null, executor: null, moloch: null): EventFilter;

    ProposeAction(proposalId: null, proposer: null, moloch: null): EventFilter;
  };

  estimateGas: {
    actions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "actions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelAction(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelAction(uint256,address)"(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeAction(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeAction(uint256,address)"(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeTribute(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "proposeTribute(address,address,address,uint256,address,uint256,string)"(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    actions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "actions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelAction(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelAction(uint256,address)"(
      _proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeAction(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeAction(uint256,address)"(
      proposalId: BigNumberish,
      molochAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeTribute(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "proposeTribute(address,address,address,uint256,address,uint256,string)"(
      applicant: string,
      molochAddress: string,
      tokenAddress: string,
      tokenId: BigNumberish,
      vaultAddress: string,
      requestAmount: BigNumberish,
      details: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
